### ISSUE TITLE
HRMS - Tempating Changes

### ISSUE THREAD

**Issue by hrmsptgindia** [PTG-INDIA/HRMS-Version-1.0#6]
Business changes  : 
By removing all the Code from View.jsp and make includes for the code and 
keep all code respective pages .

Create header jsp  :  which has all header data and body jsp which has tab content and in body jsp we should have respective tabs pages data .

once u commit the changes , update this ticket .

**Comment by NikithaJayam** [comment]
I am started working on the Issue

**Comment by NikithaJayam** [comment]
Hi @karthiksuraparaju , I have completed the ticket and committed the code can you please verify once.

**Comment by hrmsptgindia** [comment]
@NikithaJayam : looks good , follow the same , closing the issue as it meets the requirement .
